# Site Settings
title: My Personal Webpage
email: edsongarcianghelo@hotmail.com
description: A personal webpage to upload assigment from BUAA and more.

#Personal information
author:
 name: Edson Garcia
 bio: Physicist and Remote Sensing Specialist
 email: edsongarcianghelo@hotmail.com

#Build Settings
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
