# Site Settings
title: My Personal Webpage
email: edsongarcianghelo@hotmail.com
description: A personal webpage to upload assigment from BUAA and more.

#Personal information
author: Edson Garcia


#Build Settings
markdown: kramdown
theme: minima

