# Site Settings
title: My Personal Webpage
email: edsongarcianghelo@hotmail.com
description: A personal webpage to upload assigment from BUAA and more.

#Personal information
author: Edson Garcia


#Build Settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
